name: Hello World

# Controls when the workflow will run
on: [push]
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:    
    #- uses: actions/checkout@v2    
     - name: Run pwd      
       run: pwd    
     - name: Run ls -al      
       run: ls -al 
